// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD67CF3FI-G7RHnsSL-xrMKL1r3johFwUg',
    appId: '1:71508890687:android:23c2334b003a71ac8f948a',
    messagingSenderId: '71508890687',
    projectId: 'breakpoint-dc13d',
    storageBucket: 'breakpoint-dc13d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVt0WzOyr-iGhcXriC-R93rqey75FKhM',
    appId: '1:71508890687:ios:0ea7c4dc46fb9e9c8f948a',
    messagingSenderId: '71508890687',
    projectId: 'breakpoint-dc13d',
    storageBucket: 'breakpoint-dc13d.firebasestorage.app',
    iosBundleId: 'com.example.flutterSampleOne',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfSqECey9rcfBjZEjeTsrrnzwNHQ4W7g',
    appId: '1:71508890687:web:67d205c028fbf5898f948a',
    messagingSenderId: '71508890687',
    projectId: 'breakpoint-dc13d',
    authDomain: 'breakpoint-dc13d.firebaseapp.com',
    storageBucket: 'breakpoint-dc13d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVt0WzOyr-iGhcXriC-R93rqey75FKhM',
    appId: '1:71508890687:ios:0ea7c4dc46fb9e9c8f948a',
    messagingSenderId: '71508890687',
    projectId: 'breakpoint-dc13d',
    storageBucket: 'breakpoint-dc13d.firebasestorage.app',
    iosBundleId: 'com.example.flutterSampleOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBfSqECey9rcfBjZEjeTsrrnzwNHQ4W7g',
    appId: '1:71508890687:web:3f931f03d0aa7dbc8f948a',
    messagingSenderId: '71508890687',
    projectId: 'breakpoint-dc13d',
    authDomain: 'breakpoint-dc13d.firebaseapp.com',
    storageBucket: 'breakpoint-dc13d.firebasestorage.app',
  );

}